
CREATE SCHEMA IF NOT EXISTS HospitalProyecto;
USE HospitalProyecto;

CREATE TABLE IF NOT EXISTS USUARIO (
  id_Usuario VARCHAR(40) NOT NULL,
  Nombre_Usuario VARCHAR(45) NULL,
  Dpi_Usuario VARCHAR(45) NULL,
  Telefono_Usuario VARCHAR(45) NULL,
  Correo_Usuario VARCHAR(45) NULL,
  Contraseña_Usuario VARCHAR(45) NULL,
  Tipo_Usuario INT NULL,
  PRIMARY KEY (id_Usuario));

CREATE TABLE IF NOT EXISTS PACIENTE (
  id_Usuario VARCHAR(40) NOT NULL,
  Sexo_Paciente VARCHAR(45) NOT NULL,
  Fecha_Nacimiento DATE NOT NULL,
  Peso_Paciente VARCHAR(45) NOT NULL,
  Tipo_Sangre VARCHAR(45) NOT NULL,
  PRIMARY KEY (id_Usuario),
  CONSTRAINT fk_PACIENTE_USUARIO1
    FOREIGN KEY (id_Usuario)
    REFERENCES USUARIO (id_Usuario));

CREATE TABLE IF NOT EXISTS DOCTOR (
  id_Usuario VARCHAR(40) NOT NULL,
  Num_Colegiado INT NULL,
  Horario_Atencion TIME NULL,
  Horario_Salida TIME NULL,
  Fecha_Inicio DATE NULL,
  PRIMARY KEY (id_Usuario),
  CONSTRAINT fk_DOCTOR_USUARIO1
    FOREIGN KEY (id_Usuario)
    REFERENCES USUARIO (id_Usuario));

CREATE TABLE IF NOT EXISTS EXAMEN (
  Id_Examen INT NOT NULL,
  Nombre_Examen VARCHAR(180) NULL,
  Orden_Examen BOOLEAN NULL,
  Descripcion_Examen VARCHAR(45) NULL,
  Costo_Examen DOUBLE NULL,
  Informe_Examen VARCHAR(45) NULL,
  PRIMARY KEY (Id_Examen));

CREATE TABLE IF NOT EXISTS LABORATORISTA (
  id_Usuario VARCHAR(40) NOT NULL,
  Registro_Ministerio VARCHAR(45) NULL,
  Nombre_Examen VARCHAR(180) NULL,
  Fecha_Inicio DATE NULL,
  EXAMEN_Id_Examen INT NOT NULL,
  PRIMARY KEY (id_Usuario),
  CONSTRAINT fk_LABORATORISTA_USUARIO1
    FOREIGN KEY (id_Usuario)
    REFERENCES USUARIO (id_Usuario),
  CONSTRAINT fk_LABORATORISTA_EXAMEN1
    FOREIGN KEY (EXAMEN_Id_Examen)
    REFERENCES EXAMEN (Id_Examen));

CREATE TABLE IF NOT EXISTS ADMINISTRADOR (
  id_Usuario VARCHAR(40) NOT NULL,
  PRIMARY KEY (id_Usuario),
  CONSTRAINT fk_ADMINISTRADOR_USUARIO1
    FOREIGN KEY (id_Usuario)
    REFERENCES USUARIO (id_Usuario));

CREATE TABLE IF NOT EXISTS CITA (
  Id_Cita INT NOT NULL AUTO_INCREMENT,
  PACIENTE_id_Usuario VARCHAR(40) NOT NULL,
  LABORATORISTA_id_Usuario VARCHAR(40) NOT NULL,
  Fecha_Cita DATE NULL,
  Hora_Cita TIME NULL,
  PRIMARY KEY (Id_Cita),
  CONSTRAINT fk_CITA_LABORATORISTA1
    FOREIGN KEY (LABORATORISTA_id_Usuario)
    REFERENCES LABORATORISTA (id_Usuario),
  CONSTRAINT fk_CITA_PACIENTE1
    FOREIGN KEY (PACIENTE_id_Usuario)
    REFERENCES PACIENTE (id_Usuario));

CREATE TABLE IF NOT EXISTS CONSULTA (
  Tipo_Consulta VARCHAR(180) NOT NULL,
  Costo_Consulta DOUBLE NULL,
  PRIMARY KEY (Tipo_Consulta));

CREATE TABLE IF NOT EXISTS ESPECIALIDAD (
  id_Especialidad INT NOT NULL AUTO_INCREMENT,
  Nombre_Especialidad VARCHAR(300) NOT NULL,
  DOCTOR_id_Usuario VARCHAR(40) NOT NULL,
  PRIMARY KEY (id_Especialidad),
  CONSTRAINT fk_ESPECIALIDAD_DOCTOR1
    FOREIGN KEY (DOCTOR_id_Usuario)
    REFERENCES DOCTOR (id_Usuario));

CREATE TABLE IF NOT EXISTS INFORME (
  Id_Informe INT NOT NULL,
  PACIENTE_id_Usuario VARCHAR(40) NOT NULL,
  DOCTOR_id_Usuario VARCHAR(40) NOT NULL,
  Descripcion_Informe VARCHAR(1000) NULL,
  Fecha_Informe DATE NULL,
  Hora_Informe TIME NULL,
  PRIMARY KEY (Id_Informe),
  CONSTRAINT fk_INFORME_DOCTOR1
    FOREIGN KEY (DOCTOR_id_Usuario)
    REFERENCES DOCTOR (id_Usuario),
  CONSTRAINT fk_INFORME_PACIENTE1
    FOREIGN KEY (PACIENTE_id_Usuario)
    REFERENCES PACIENTE (id_Usuario));


CREATE TABLE IF NOT EXISTS RESULTADO (
  Id_Resultado INT NOT NULL AUTO_INCREMENT,
  PACIENTE_id_Usuario VARCHAR(40) NOT NULL,
  DOCTOR_id_Usuario VARCHAR(40) NULL,
  EXAMEN_Id_Examen INT NOT NULL,
  LABORATORISTA_id_Usuario VARCHAR(40) NOT NULL,
  Orden_Resultado VARCHAR(400) NULL,
  Informe_Resultado VARCHAR(400) NULL,
  Fecha_Resultado DATE NULL,
  Hora_Resultado TIME NULL,
  PRIMARY KEY (Id_Resultado),
  CONSTRAINT fk_RESULTADO_EXAMEN1
    FOREIGN KEY (EXAMEN_Id_Examen)
    REFERENCES EXAMEN (Id_Examen),
  CONSTRAINT fk_RESULTADO_LABORATORISTA1
    FOREIGN KEY (LABORATORISTA_id_Usuario)
    REFERENCES LABORATORISTA (id_Usuario),
  CONSTRAINT fk_RESULTADO_PACIENTE1
    FOREIGN KEY (PACIENTE_id_Usuario)
    REFERENCES PACIENTE (id_Usuario),
  CONSTRAINT fk_RESULTADO_DOCTOR1
    FOREIGN KEY (DOCTOR_id_Usuario)
    REFERENCES DOCTOR (id_Usuario));


CREATE TABLE IF NOT EXISTS DIAS_TRABAJO (
  Id_Dias INT NOT NULL AUTO_INCREMENT,
  Dias_Trabajo VARCHAR(45) NULL,
  LABORATORISTA_id_Usuario VARCHAR(40) NOT NULL,
  PRIMARY KEY (Id_Dias),
  CONSTRAINT fk_DIAS_TRABAJO_LABORATORISTA1
    FOREIGN KEY (LABORATORISTA_id_Usuario)
    REFERENCES LABORATORISTA (id_Usuario));

CREATE TABLE IF NOT EXISTS CITA_DOCTOR (
  Id_CitaDoctor INT NOT NULL AUTO_INCREMENT,
  PACIENTE_id_Usuario VARCHAR(40) NOT NULL,
  DOCTOR_id_Usuario VARCHAR(40) NOT NULL,
  CONSULTA_Tipo_Consulta VARCHAR(180) NOT NULL,
  Fecha_CitaD DATE NULL,
  Hora_CitaD TIME NULL,
  PRIMARY KEY (Id_CitaDoctor),
  CONSTRAINT fk_CITA_DOCTOR_CONSULTA1
    FOREIGN KEY (CONSULTA_Tipo_Consulta)
    REFERENCES CONSULTA (Tipo_Consulta),
  CONSTRAINT fk_CITA_DOCTOR_DOCTOR1
    FOREIGN KEY (DOCTOR_id_Usuario)
    REFERENCES DOCTOR (id_Usuario),
  CONSTRAINT fk_CITA_DOCTOR_PACIENTE1
    FOREIGN KEY (PACIENTE_id_Usuario)
    REFERENCES PACIENTE (id_Usuario));

CREATE TABLE IF NOT EXISTS GANANCIAS_LAB (
  Id_Ganancias INT NOT NULL AUTO_INCREMENT,
  PACIENTE_id_Usuario VARCHAR(40) NULL,
  LABORATORISTA_id_Usuario VARCHAR(40) NULL,
  Fecha_Ganancias DATE NULL,
  Total_Ganancias DOUBLE NULL,
  CITA_Id_Cita INT NULL,
  PRIMARY KEY (Id_Ganancias),
  CONSTRAINT fk_GANANCIAS_LAB_LABORATORISTA1
    FOREIGN KEY (LABORATORISTA_id_Usuario)
    REFERENCES LABORATORISTA (id_Usuario),
  CONSTRAINT fk_GANANCIAS_LAB_PACIENTE1
    FOREIGN KEY (PACIENTE_id_Usuario)
    REFERENCES PACIENTE (id_Usuario),
  CONSTRAINT fk_GANANCIAS_LAB_CITA1
    FOREIGN KEY (CITA_Id_Cita)
    REFERENCES CITA (Id_Cita));

CREATE TABLE IF NOT EXISTS GANANCIAS_DOCTOR (
  Id_GananciasD INT NOT NULL AUTO_INCREMENT,
  PACIENTE_id_Usuario VARCHAR(40) NULL,
  DOCTOR_id_Usuario VARCHAR(40) NULL,
  Fecha_GananciasD DATE NULL,
  Total_GananciasD DOUBLE NULL,
  CITA_DOCTOR_Id_CitaDoctor INT NOT NULL,
  PRIMARY KEY (Id_GananciasD),
  CONSTRAINT fk_GANANCIAS_DOCTOR_DOCTOR1
    FOREIGN KEY (DOCTOR_id_Usuario)
    REFERENCES DOCTOR (id_Usuario),
  CONSTRAINT fk_GANANCIAS_DOCTOR_PACIENTE1
    FOREIGN KEY (PACIENTE_id_Usuario)
    REFERENCES PACIENTE (id_Usuario),
  CONSTRAINT fk_GANANCIAS_DOCTOR_CITA_DOCTOR1
    FOREIGN KEY (CITA_DOCTOR_Id_CitaDoctor)
    REFERENCES CITA_DOCTOR (Id_CitaDoctor));


